export const ADD_ALARM = "ADD_ALARM";
export const DELETE_ALARM = "DELETE_ALARM";
export const DELETE_ALL_ALARMS = "DELETE_ALL_ALARMS";
export const SET_ALARMS = "SET_ALARMS";
export const ADD_QUOTE_TO_FAV_QUOTES = "ADD_QUOTE_TO_FAV_QUOTES";
export const DELETE_QUOTE_TO_FAV_QUOTES = "DELETE_QUOTE_TO_FAV_QUOTES";
